### ISSUE TITLE
[Questions] HystrixCommand Design Implementation 

### ISSUE THREAD

**Issue by kolbis** [Travix-International/Hystrix.Dotnet#18]
On Netfix java port, you wrap each "critical code" with a command. In other words, you need to create a new class which inherits from HystrixCommand and place your execute and fallback logic inside this class.
The approach which was selected for this port differs, so you do not need to create command classes.  
1. Why was this design was prefer?

IMHO, having also the "inheritance" approach is valuable and provides more flexibility and readability (especially for complex behaviors).
2. What is your take on that? would that something you consider supporting?

My last question refers to production readiness of this port.
3. Do you have this port already running on large scale production environments?
 
Thanks!

**Comment by markvincze** [comment]
Hi @kolbis,

I'm not sure why this design was chosen, I assume it was due to simplicity, so that we don't have to implement a derived type for every command. Maybe that's easier to do in Java thanks to the ability to create anonymous implementations for abstract base classes?
@JorritSalverda, can you chime in on this one?

As to your last question: we are running this on production in many APIs, and multiple commands are handling over 100 requests per second.

**Comment by JorritSalverda** [comment]
I did this mostly because I'm not a big fan of inheritance. I definitely favour composition over inheritance - although that doesn't really apply here as there's little composition going on :) -  after having seen so many bad uses of inheritance cornering big software projects into a certain solution without an easy way out.

**Comment by kolbis** [comment]
Thank you both for the responses.
The original implementation of Netflix is using inheritance (and IMHO this makes sense in this case, in order to keep code cleaner).
